# @package _global_

# specify here default training configuration
defaults:
  - data: 
    - imdb_20news_3splits
  - emb_model:
    - doc2vec_apnews
  - dim_red: 
    - umap
  - od_det: 
    - autoencoder
  - experiment: null


# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/
model_dir: ${work_dir}/models/
result_dir: ${work_dir}/reports/eval_runs/

