apnews:
  _target_: src.embedders.Doc2VecModel
  model_path: ${model_dir}/apnews_dbow/doc2vec.bin
  model_name: Doc2Vec_APNews
  model_train_data: APNews
  doc2vec_data_frac: 1.0
  doc2vec_epochs: 100
  doc2vec_min_count: 1
  model_type: doc2vec